// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmT1I-6eal4oeboiBzZgZyxSC9HJm00g4',
    appId: '1:903892114230:web:e5a82af521351c82577197',
    messagingSenderId: '903892114230',
    projectId: 'shareeat-d999c',
    authDomain: 'shareeat-d999c.firebaseapp.com',
    storageBucket: 'shareeat-d999c.firebasestorage.app',
    measurementId: 'G-ZES19HNG6S',
    databaseURL: 'https://shareeat-d999c-default-rtdb.asia-southeast1.firebasedatabase.app',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2iFmW5E0TE37Nf4YsaaFUUbZQ73o2OAo',
    appId: '1:903892114230:android:4d9dfb755cc37896577197',
    messagingSenderId: '903892114230',
    projectId: 'shareeat-d999c',
    storageBucket: 'shareeat-d999c.firebasestorage.app',
    databaseURL: 'https://shareeat-d999c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-4Em-lfgC6kLCJhmPgSn0UBJNCZx8vtQ',
    appId: '1:903892114230:ios:8fd98d10e7180682577197',
    messagingSenderId: '903892114230',
    projectId: 'shareeat-d999c',
    storageBucket: 'shareeat-d999c.firebasestorage.app',
    iosBundleId: 'com.example.shareeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-4Em-lfgC6kLCJhmPgSn0UBJNCZx8vtQ',
    appId: '1:903892114230:ios:8fd98d10e7180682577197',
    messagingSenderId: '903892114230',
    projectId: 'shareeat-d999c',
    storageBucket: 'shareeat-d999c.firebasestorage.app',
    iosBundleId: 'com.example.shareeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmT1I-6eal4oeboiBzZgZyxSC9HJm00g4',
    appId: '1:903892114230:web:ce7e83c7f9d9e65d577197',
    messagingSenderId: '903892114230',
    projectId: 'shareeat-d999c',
    authDomain: 'shareeat-d999c.firebaseapp.com',
    storageBucket: 'shareeat-d999c.firebasestorage.app',
    measurementId: 'G-456HVSL1C3',
  );
}
